// Auto-generated by concat_tb_for_eda_playground.ps1
// Paste this into the EDA Playground Testbench pane.


//====================================================
// Source: tb/spi_if.sv
//====================================================
//=============================================================================
// File        : spi_if.sv
// Description : SystemVerilog interface that bundles together all signals
//               connecting the testbench to the SPI_Slave DUT.
//
//               Two clock domains exist on this DUT:
//                 - i_Clk      : the "system" clock (fast, FPGA-side clock)
//                 - i_SPI_Clk  : the SPI bus clock, driven by the SPI master
//                                (in our case, driven by the driver, since
//                                we are verifying a SPI SLAVE and there is
//                                no real master in the testbench)
//
//               Keeping all DUT signals in one interface avoids passing
//               a huge list of ports around every class, and lets us
//               attach protocol assertions directly to the interface.
//=============================================================================

interface spi_if (input logic i_Clk);

  // ---------------------------------------------------------------------
  // System clock domain signals
  // ---------------------------------------------------------------------
  logic        i_Rst_L;     // active-low system reset

  logic        o_RX_DV;     // pulses high for 1 clk when o_RX_Byte is valid
  logic [7:0]  o_RX_Byte;   // byte received from SPI master (on MOSI)

  logic        i_TX_DV;     // driver pulses this to load next TX byte
  logic [7:0]  i_TX_Byte;   // byte to be shifted out to SPI master (on MISO)

  // ---------------------------------------------------------------------
  // SPI bus signals (driven by our testbench, acting as the SPI Master)
  // ---------------------------------------------------------------------
  logic        i_SPI_Clk;   // SPI bus clock, driven by testbench (as master)
  logic        o_SPI_MISO;  // driven BY the DUT (slave), sampled by monitor
  logic        i_SPI_MOSI;  // driven by testbench (as master)
  logic        i_SPI_CS_n;  // active-low chip select, driven by testbench

  // ---------------------------------------------------------------------
  // Modport for the driver: drives SPI bus + system-side TX signals
  // ---------------------------------------------------------------------
  modport DRIVER (
    input i_Clk,
    output i_Rst_L,
    output i_SPI_Clk,
    output i_SPI_MOSI,
    output i_SPI_CS_n,
    output i_TX_DV,
    output i_TX_Byte,
    input  o_SPI_MISO,
    input  o_RX_DV,
    input  o_RX_Byte
  );

  // ---------------------------------------------------------------------
  // Modport for the monitor: only observes signals, drives nothing
  // ---------------------------------------------------------------------
  modport MONITOR (
    input i_Clk,
    input i_Rst_L,
    input i_SPI_Clk,
    input i_SPI_MOSI,
    input i_SPI_CS_n,
    input o_SPI_MISO,
    input o_RX_DV,
    input o_RX_Byte,
    input i_TX_DV,
    input i_TX_Byte
  );

endinterface : spi_if

//====================================================
// Source: assertions/spi_assertions.sv
//====================================================
//=============================================================================
// File        : spi_assertions.sv
// Description : Beginner/intermediate-level SystemVerilog Assertions (SVA)
//               for the SPI Slave DUT protocol. Bound into top_tb.sv as a
//               separate module (not embedded inside the DUT, since the
//               DUT is treated as black-box RTL from the design team).
//
//               Checks covered (see docs/verification_plan.md):
//                 A1 - o_RX_DV is exactly one clock cycle wide
//                 A2 - o_RX_DV is never asserted while in reset
//                 A3 - o_SPI_MISO is high-impedance while CS_n is high
//                 A4 - MOSI must be stable while SPI clock is high
//                      (Mode 0: data sampled on rising edge, so it must
//                      not change while SCLK is high)
//                 A5 - i_SPI_CS_n must not glitch (stay low) for at
//                      least one full SPI clock period once asserted
//                 A6 - after reset is released, o_RX_DV must not be
//                      asserted until a real transfer happens
//=============================================================================

module spi_assertions (
  input logic       i_Clk,
  input logic       i_Rst_L,
  input logic       i_SPI_Clk,
  input logic       i_SPI_MOSI,
  input logic       i_SPI_CS_n,
  input logic       o_SPI_MISO,
  input logic       o_RX_DV,
  input logic [7:0] o_RX_Byte
);

  // -------------------------------------------------------------------
  // A1: o_RX_DV must be exactly 1 clock cycle wide (pulses high for
  // one i_Clk period, then must go back low on the very next edge)
  // -------------------------------------------------------------------
  property p_rx_dv_one_cycle_pulse;
    @(posedge i_Clk) disable iff (!i_Rst_L)
      o_RX_DV |=> !o_RX_DV;
  endproperty

  a_rx_dv_one_cycle_pulse : assert property (p_rx_dv_one_cycle_pulse)
    else $error("[ASSERT] A1 FAILED: o_RX_DV stayed high for more than 1 cycle at time %0t", $time);

  // -------------------------------------------------------------------
  // A2: o_RX_DV must never be asserted while the DUT is held in reset
  // -------------------------------------------------------------------
  property p_no_rx_dv_during_reset;
    @(posedge i_Clk)
      (!i_Rst_L) |-> !o_RX_DV;
  endproperty

  a_no_rx_dv_during_reset : assert property (p_no_rx_dv_during_reset)
    else $error("[ASSERT] A2 FAILED: o_RX_DV asserted while i_Rst_L is low at time %0t", $time);

  // -------------------------------------------------------------------
  // A3: o_SPI_MISO must be high-impedance ('z') whenever CS_n is high
  // (deasserted), so multiple slaves can safely share the MISO line.
  // -------------------------------------------------------------------
  property p_miso_tristate_when_cs_high;
    @(posedge i_Clk)
      (i_SPI_CS_n) |-> (o_SPI_MISO === 1'bz);
  endproperty

  a_miso_tristate_when_cs_high : assert property (p_miso_tristate_when_cs_high)
    else $error("[ASSERT] A3 FAILED: o_SPI_MISO is not high-Z while i_SPI_CS_n is high at time %0t", $time);

  // -------------------------------------------------------------------
  // A4: In SPI Mode 0, MOSI must not change while SCLK is high, since
  // the DUT samples MOSI on the rising edge and expects the value held
  // through the entire high phase. Written as an immediate assertion
  // inside an always block (triggered only when MOSI actually toggles)
  // rather than a concurrent property, since this is easier for a
  // fresher to read and reason about, and avoids edge-alignment
  // subtleties of comparing samples across two different clock edges.
  // -------------------------------------------------------------------
  always @(i_SPI_MOSI) begin
    if (i_SPI_Clk === 1'b1 && i_SPI_CS_n === 1'b0) begin
      a_mosi_stable_while_sclk_high : assert (0)
        else $error("[ASSERT] A4 FAILED: i_SPI_MOSI changed while i_SPI_Clk was high at time %0t", $time);
    end
  end

  // -------------------------------------------------------------------
  // A5: Once CS_n is asserted (low), at least one SPI clock rising edge
  // must occur before CS_n goes back high - protects against a
  // testbench (or DUT) bug that pulses CS_n too briefly to be a legal
  // SPI transaction. Implemented with a simple edge counter rather than
  // a concurrent property, since the "wait for an edge on a different
  // clock before this clock's next event" check is awkward to express
  // cleanly as a property and much clearer as plain RTL-style code.
  // -------------------------------------------------------------------
  int sclk_edge_count;

  always @(negedge i_SPI_CS_n) begin
    sclk_edge_count <= 0;   // new burst starting, reset counter
  end

  always @(posedge i_SPI_Clk) begin
    if (!i_SPI_CS_n) sclk_edge_count <= sclk_edge_count + 1;
  end

  always @(posedge i_SPI_CS_n) begin
    if (i_Rst_L) begin
        a_cs_n_min_low_time : assert (sclk_edge_count >= 1)
            else
                $error("[ASSERT] A5 FAILED: i_SPI_CS_n was deasserted before any SPI clock edge occurred at time %0t", $time);
    end
end 

  // -------------------------------------------------------------------
  // A6: After reset is released, o_RX_DV must not be asserted unless
  // CS_n was low (a real transfer was happening) at some point in the
  // recent past. This is a simple sanity check that the DUT never
  // reports "data received" out of nowhere with no bus activity.
  // -------------------------------------------------------------------
  property p_rx_dv_needs_real_transfer;
    @(posedge i_Clk) disable iff (!i_Rst_L)
      o_RX_DV |-> $past(i_SPI_CS_n) === 1'b0;
  endproperty

  a_rx_dv_needs_real_transfer : assert property (p_rx_dv_needs_real_transfer)
    else $error("[ASSERT] A6 FAILED: o_RX_DV asserted without a preceding CS_n-low transfer at time %0t", $time);

endmodule : spi_assertions

//====================================================
// Source: tb/transaction.sv
//====================================================
//=============================================================================
// File        : transaction.sv
// Description : Transaction (sequence item) class for the SPI Slave TB.
//
//               One transaction = one SPI byte transfer. Since this DUT
//               supports multiple bytes per CS_n assertion (back-to-back
//               transfers while CS stays low), we also model that at the
//               generator level by issuing several transactions with
//               cs_hold_after = 1.
//
//               This class is intentionally simple: no factory, no
//               inheritance tricks. Just a plain class with randomizable
//               fields, constraints, and a print/copy helper - exactly
//               what a fresher-built non-UVM environment should look like.
//=============================================================================

class transaction;

  // -------------------------------------------------------------------
  // Data fields
  // -------------------------------------------------------------------
  rand bit [7:0] mosi_data;     // byte driven from master -> slave (MOSI)
  rand bit [7:0] miso_data;     // byte pre-loaded into slave for MISO
                                 // (this is what the driver writes into
                                 //  i_TX_Byte/i_TX_DV before the transfer)

  // Controls whether CS_n stays LOW after this byte (back-to-back mode)
  // or goes HIGH (ends the transaction) after this byte.
  rand bit       cs_hold_after;

  // Which SPI mode to use for this transaction (0,1,2,3).
  // Kept constant for most tests, randomized only in the SPI-mode test.
  rand bit [1:0] spi_mode;

  // -------------------------------------------------------------------
  // Constraints
  // -------------------------------------------------------------------

  // By default, favor ending the transaction (cs_hold_after = 0) about
  // half the time, and continuing back-to-back the other half. This gives
  // the random test a healthy mix of single-byte and multi-byte bursts.
  constraint c_cs_hold_dist {
    cs_hold_after dist { 0 := 50, 1 := 50 };
  }

  // Keep spi_mode at 0 unless a test explicitly randomizes it separately.
  // (Mode is normally a static DUT parameter, not something that changes
  // mid-simulation on real hardware, so most tests hold this fixed.)
  constraint c_default_mode {
    spi_mode == 2'b00;
  }

  // -------------------------------------------------------------------
  // Utility: deep copy
  // -------------------------------------------------------------------
  function transaction copy();
    transaction t = new();
    t.mosi_data     = this.mosi_data;
    t.miso_data     = this.miso_data;
    t.cs_hold_after = this.cs_hold_after;
    t.spi_mode      = this.spi_mode;
    return t;
  endfunction

  // -------------------------------------------------------------------
  // Utility: readable print for logging/debug
  // -------------------------------------------------------------------
  function void print(string tag = "TXN");
    $display("[%0s] mosi_data=0x%0h miso_data=0x%0h cs_hold_after=%0b spi_mode=%0d",
              tag, mosi_data, miso_data, cs_hold_after, spi_mode);
  endfunction

endclass : transaction

//====================================================
// Source: tb/generator.sv
//====================================================
//=============================================================================
// File        : generator.sv
// Description : Generates transactions and sends them to the driver via a
//               mailbox. Supports:
//                 - fully random generation (num_txns randomized bytes)
//                 - directed generation (a specific queue of transactions,
//                   used for smoke test / corner cases / specific patterns)
//
//               Kept as a plain class (no uvm_sequence, no macros) so the
//               control flow is easy to read top-to-bottom.
//=============================================================================

class generator;

  mailbox #(transaction) gen2drv_mbx;  // handle to driver's inbox
  event                  drv_done;     // driver signals back when it is done
                                        // with all queued transactions (used
                                        // by the test to know when to finish)

  int num_txns = 10;   // number of random transactions to generate

  function new(mailbox #(transaction) gen2drv_mbx, event drv_done);
    this.gen2drv_mbx = gen2drv_mbx;
    this.drv_done    = drv_done;
  endfunction

  // -------------------------------------------------------------------
  // run_random: generate 'num_txns' fully randomized transactions
  // -------------------------------------------------------------------
  task run_random();
    transaction txn;
    for (int i = 0; i < num_txns; i++) begin
      txn = new();
      if (!txn.randomize()) begin
        $error("[GENERATOR] Randomization failed for txn %0d", i);
      end
      // Last transaction in the burst should always end the CS cycle,
      // otherwise the run would never deassert CS_n.
      if (i == num_txns - 1) txn.cs_hold_after = 1'b0;

      txn.print("GEN");
      gen2drv_mbx.put(txn);
    end
  endtask

  // -------------------------------------------------------------------
  // run_directed: send a pre-built queue of transactions (used by
  // smoke test, corner-case test, data-pattern test, etc.)
  // -------------------------------------------------------------------
  task run_directed(transaction txn_q[$]);
    foreach (txn_q[i]) begin
      txn_q[i].print("GEN-DIR");
      gen2drv_mbx.put(txn_q[i]);
    end
  endtask

endclass : generator

//====================================================
// Source: tb/scoreboard.sv
//====================================================
//=============================================================================
// File        : scoreboard.sv
// Description : Checks that the SPI Slave DUT behaves correctly by
//               comparing:
//
//                 1) What the monitor observed on the MOSI line (the byte
//                    the "master" sent) against the byte the DUT reports
//                    on o_RX_Byte (in the i_Clk domain, via o_RX_DV pulse).
//
//                 2) What the monitor observed on the MISO line (the byte
//                    the DUT actually shifted out) against the byte that
//                    was pre-loaded into the DUT via i_TX_Byte/i_TX_DV
//                    for that transfer.
//
//               This scoreboard is intentionally simple: an in-order
//               transaction-level comparison using mailboxes plus a
//               scoreboard-local reference queue. No fancy pending-CAM
//               or associative-array pattern is used, because SPI in
//               this environment is inherently in-order and single-
//               threaded (one byte transfer completes before the next
//               starts).
//=============================================================================

class scoreboard;

  virtual spi_if.MONITOR vif;
  mailbox #(transaction) mon2scb_mbx;

  // Reference queue of "expected MISO byte" values, pushed by the driver
  // side (through the environment) each time it preloads i_TX_Byte for
  // an upcoming transfer. The scoreboard pops one entry per observed
  // transaction to know what MISO *should* have been.
  bit [7:0] expected_miso_q[$];

  // Mailbox used to hand off each observed MOSI byte from
  // check_miso_transactions() to check_mosi_against_rx_dv(), so the
  // RX-path check blocks until the monitor has actually recorded the
  // byte instead of racing ahead of it.
  mailbox #(bit [7:0]) last_mosi_seen_mbx;

  int num_checked = 0;
  int num_passed  = 0;
  int num_failed  = 0;

  function new(virtual spi_if.MONITOR vif,
               mailbox #(transaction) mon2scb_mbx);
    this.vif              = vif;
    this.mon2scb_mbx      = mon2scb_mbx;
    this.last_mosi_seen_mbx = new();
  endfunction

  // Called by the environment/driver whenever a new MISO byte is
  // preloaded, so the scoreboard knows what to expect.
  function void push_expected_miso(bit [7:0] data);
    expected_miso_q.push_back(data);
  endfunction

  // -------------------------------------------------------------------
  // run: main scoreboard loop. Also independently watches o_RX_DV in
  // the i_Clk domain to cross-check the DUT's own reported RX byte
  // against what the monitor captured directly off the MOSI line.
  // -------------------------------------------------------------------
  task run();
    fork
      check_mosi_against_rx_dv();
      check_miso_transactions();
    join_none
  endtask

  // ---------------------------------------------------------------
  // check_mosi_against_rx_dv:
  // Independently samples o_RX_DV/o_RX_Byte and compares it against
  // the MOSI byte last observed by the monitor. This directly
  // verifies the DUT's clock-domain-crossing logic (SPI clock domain
  // -> system clock domain) is reporting the correct byte.
  // ---------------------------------------------------------------
  task check_mosi_against_rx_dv();
    forever begin
      @(posedge vif.i_Clk);
      if (vif.o_RX_DV) begin
        bit [7:0] exp_mosi;

        num_checked++;

        // Wait until the monitor has provided the corresponding MOSI byte.
        last_mosi_seen_mbx.get(exp_mosi);

        if (vif.o_RX_Byte === exp_mosi) begin
          $display("[SCOREBOARD] PASS (RX path): DUT received 0x%02h", exp_mosi);
          num_passed++;
        end
        else begin
          $error("[SCOREBOARD] FAIL (RX path): DUT received=0x%02h expected=0x%02h",
                 vif.o_RX_Byte, exp_mosi);
          num_failed++;
        end
      end
    end
  endtask

  // ---------------------------------------------------------------
  // check_miso_transactions:
  // Consumes monitor transactions (mosi_data/miso_data pairs captured
  // directly off the bus) and:
  //   - records the mosi_data into last_mosi_seen_mbx for RX-path check
  //   - compares miso_data against the expected preloaded TX byte
  // ---------------------------------------------------------------
  task check_miso_transactions();
    transaction txn;
    forever begin
      mon2scb_mbx.get(txn);
      last_mosi_seen_mbx.put(txn.mosi_data);

      num_checked++;
      if (expected_miso_q.size() == 0) begin
        $warning("[SCOREBOARD] MISO observed=0x%0h but no expected value was pushed (check testbench sequencing)",
                  txn.miso_data);
      end
      else begin
        bit [7:0] exp_miso = expected_miso_q.pop_front();
        if (txn.miso_data === exp_miso) begin
          num_passed++;
          $display("[SCOREBOARD] PASS (TX path): MISO observed=0x%0h matches expected=0x%0h",
                    txn.miso_data, exp_miso);
        end
        else begin
          num_failed++;
          $error("[SCOREBOARD] FAIL (TX path): MISO observed=0x%0h != expected=0x%0h",
                  txn.miso_data, exp_miso);
        end
      end
    end
  endtask

  // -------------------------------------------------------------------
  // report: print final pass/fail summary. Called at end of test.
  // -------------------------------------------------------------------
  function void report();
    $display("=========================================================");
    $display("[SCOREBOARD] FINAL REPORT");
    $display("  Total Checks : %0d", num_checked);
    $display("  Passed       : %0d", num_passed);
    $display("  Failed       : %0d", num_failed);
    if (num_failed == 0)
      $display("  RESULT       : TEST PASSED");
    else
      $display("  RESULT       : TEST FAILED");
    $display("=========================================================");
  endfunction

endclass : scoreboard 

//====================================================
// Source: tb/driver.sv
//====================================================
//=============================================================================
// File        : driver.sv
// Description : Drives transactions onto the SPI bus. Since the DUT is a
//               SPI SLAVE, the driver plays the role of the SPI MASTER:
//               it generates i_SPI_Clk, drives i_SPI_MOSI, and controls
//               i_SPI_CS_n. It also drives the system-side i_TX_Byte /
//               i_TX_DV signals to pre-load the byte the slave should
//               send back on MISO.
//
//               Only SPI Mode 0 (CPOL=0, CPHA=0) is used by default,
//               matching the DUT instantiation in top_tb.sv. This keeps
//               the driver logic simple for a fresher project - one
//               mode, clearly explained, instead of a generic 4-mode
//               bit-banger.
//
//               Mode 0 timing recap:
//                 - SCLK idles LOW
//                 - Data is sampled on the RISING edge of SCLK
//                 - Data changes on the FALLING edge of SCLK
//=============================================================================

class driver;

  virtual spi_if.DRIVER vif;
  mailbox #(transaction) gen2drv_mbx;
  event                  drv_done;

  // Handle to the scoreboard so the driver can tell it, ahead of time,
  // what MISO byte *should* come out of the DUT for each transfer
  // (the scoreboard has no other way to know what was preloaded).
  scoreboard scb;

  // Half period of the SPI clock, in time units of the simulation.
  // The system clock (i_Clk) period is defined in top_tb.sv; this SPI
  // clock is intentionally much slower than i_Clk, since the DUT
  // requires i_Clk to be at least 4x faster than i_SPI_Clk.
  time spi_half_period = 50ns; // => 10 MHz SPI clock (100ns period)

  function new(virtual spi_if.DRIVER vif,
               mailbox #(transaction) gen2drv_mbx,
               event drv_done,
               scoreboard scb);
    this.vif         = vif;
    this.gen2drv_mbx = gen2drv_mbx;
    this.drv_done    = drv_done;
    this.scb         = scb;
  endfunction

  // -------------------------------------------------------------------
  // reset_dut: apply and release reset, initialize bus to idle state
  // -------------------------------------------------------------------
  task reset_dut();
    vif.i_Rst_L    <= 1'b0;
    vif.i_SPI_CS_n <= 1'b1;   // CS idle (deasserted)
    vif.i_SPI_Clk  <= 1'b0;   // SCLK idle low (Mode 0)
    vif.i_SPI_MOSI <= 1'b0;
    vif.i_TX_DV    <= 1'b0;
    vif.i_TX_Byte  <= 8'h00;
   repeat (5) @(posedge vif.i_Clk);
vif.i_Rst_L <= 1'b1;
repeat (5) @(posedge vif.i_Clk);

// Prime the SPI slave TX path before the first real transaction
vif.i_SPI_CS_n <= 1'b0;
#(spi_half_period);

vif.i_SPI_Clk <= 1'b1;
#(spi_half_period);
vif.i_SPI_Clk <= 1'b0;

vif.i_SPI_CS_n <= 1'b1;
#(spi_half_period); 

$display("[DRIVER] Reset applied and released at time %0t", $time);
  endtask  

  // -------------------------------------------------------------------
  // preload_tx_byte: load the byte the DUT should shift out on MISO
  // for the *next* transaction, using the system clock domain.
  // -------------------------------------------------------------------
  task preload_tx_byte(bit [7:0] data);
    @(posedge vif.i_Clk);
    vif.i_TX_Byte <= data;
    vif.i_TX_DV   <= 1'b1;
    @(posedge vif.i_Clk);
    vif.i_TX_DV   <= 1'b0;

    // Tell the scoreboard what MISO should show for this transfer
    scb.push_expected_miso(data);
  endtask

  // -------------------------------------------------------------------
  // drive_byte: shifts one byte (MSB first) out on MOSI while sampling
  // MISO, using SPI Mode 0 timing. CS_n is asserted before the first
  // byte of a burst and only deasserted if cs_hold_after = 0.
  // -------------------------------------------------------------------
  task drive_byte(transaction txn, bit is_first_byte);

    // Pre-load what the slave should send back on MISO for this byte.
    preload_tx_byte(txn.miso_data);

    if (is_first_byte) begin
      vif.i_SPI_CS_n <= 1'b0;   // assert CS (active low) to start burst
      #(spi_half_period);       // small setup gap before first clock edge
    end

    for (int bit_idx = 7; bit_idx >= 0; bit_idx--) begin
      // Drive MOSI while clock is still low (data changes on falling edge,
      // sampled on rising edge - Mode 0)
      vif.i_SPI_MOSI <= txn.mosi_data[bit_idx];
      #(spi_half_period);

      vif.i_SPI_Clk <= 1'b1;    // rising edge -> DUT samples MOSI here
      #(spi_half_period);

      vif.i_SPI_Clk <= 1'b0;    // falling edge -> DUT/master change data
    end

    if (!txn.cs_hold_after) begin
      #(spi_half_period);
      vif.i_SPI_CS_n <= 1'b1;   // deassert CS, ends the transaction
      #(spi_half_period);
    end

  endtask

  // -------------------------------------------------------------------
  // run: main driver loop - pulls transactions from mailbox and drives
  // them onto the bus. Tracks whether we are mid-burst (CS already low)
  // to correctly assert CS only at the start of a new burst.
  // -------------------------------------------------------------------
  task run();
    transaction txn;
    bit         cs_currently_low = 1'b0;

    forever begin
      gen2drv_mbx.get(txn);
      txn.print("DRV");

      drive_byte(txn, !cs_currently_low);
      cs_currently_low = txn.cs_hold_after;

      // Small idle gap between independent bursts for readability in
      // waveforms and to guarantee CS pulse width is clearly visible.
      if (!txn.cs_hold_after) begin
        repeat (2) @(posedge vif.i_Clk);
      end
    end
  endtask

endclass : driver

//====================================================
// Source: tb/monitor.sv
//====================================================
//=============================================================================
// File        : monitor.sv
// Description : Passively watches the SPI bus (MOSI/MISO/SCLK/CS_n) and
//               reconstructs each 8-bit transfer bit-by-bit.
//
//               FINAL TIMING NOTE (root-caused after debugging a shifted
//               MISO bug, then a shifted MOSI bug caused by an earlier
//               fix attempt): MOSI and MISO are NOT stable at the same
//               instant, so they cannot be safely sampled on the same
//               clock edge. Each is sampled on the edge where the DUT
//               itself guarantees a settled, race-free value:
//
//               - MOSI is sampled on the RISING edge of i_SPI_Clk. This
//                 is exactly the edge the DUT's own RX shift register
//                 uses to sample MOSI, and the driver (acting as SPI
//                 master) never changes MOSI at this instant - it only
//                 changes MOSI right after the FALLING edge - so there
//                 is no race here.
//
//               - MISO is sampled on the FALLING edge of i_SPI_Clk, one
//                 half period AFTER the rising edge that caused the DUT
//                 to update it. The DUT's TX shift register
//                 (r_SPI_MISO_Bit, r_TX_Bit_Count) updates via a
//                 non-blocking assignment inside
//                 "always @(posedge w_SPI_Clk or posedge i_SPI_CS_n)".
//                 Sampling MISO on that SAME rising edge races that
//                 update (can read the pre-update value); sampling on
//                 the following falling edge gives the update a full
//                 half period to settle, so it is race-free.
//
//               Using the SAME edge for both signals was tried and
//               fails either way: posedge-for-both raced MISO's update
//               (0x3C observed as 0x1E); negedge-for-both raced MOSI's
//               next-bit setup, which lands in the same NBA flush as
//               the falling edge (0xA5 observed as 0x4B). Sampling each
//               signal on its own correct edge fixes both.
//
//               Two mailboxes are used:
//                 mon2scb_mbx  -> sends observed transactions to scoreboard
//                 mon2cov_mbx  -> sends observed transactions to coverage
//=============================================================================

class monitor;

  virtual spi_if.MONITOR vif;
  mailbox #(transaction) mon2scb_mbx;
  mailbox #(transaction) mon2cov_mbx;

  function new(virtual spi_if.MONITOR vif,
               mailbox #(transaction) mon2scb_mbx,
               mailbox #(transaction) mon2cov_mbx);
    this.vif          = vif;
    this.mon2scb_mbx  = mon2scb_mbx;
    this.mon2cov_mbx  = mon2cov_mbx;
  endfunction

  // -------------------------------------------------------------------
  // run: main monitor loop.
  //   1. Wait for CS_n to go low (start of a burst)
  //   2. For each byte, and for each of its 8 bits:
  //        a. wait for the RISING edge, sample MOSI (race-free there)
  //        b. wait for the following FALLING edge, sample MISO
  //           (race-free there, a half period after the DUT's update)
  //   3. After the 8th bit, race "next SCLK rising edge" (next byte's
  //      bit-0 posedge) against "CS_n rising edge" to determine whether
  //      the burst continues (cs_hold_after=1) or ends (cs_hold_after=0).
  //      If it continues, the posedge we just saw for the lookahead IS
  //      the next byte's bit-0 rising edge, so we remember it
  //      (pending_posedge_valid) instead of waiting for a second rising
  //      edge and silently dropping a bit - we still sample MOSI from
  //      it normally once the next byte's loop reaches bit_idx 0.
  //   4. Push the observed transaction into the scoreboard and
  //      coverage mailboxes.
  // -------------------------------------------------------------------
  task run();
    transaction mon_txn;
    bit [7:0]   mosi_shreg;
    bit [7:0]   miso_shreg;
    bit         pending_posedge_valid; // true: next byte's bit-0 rising
                                        // edge was already seen during
                                        // the previous byte's lookahead
    bit         burst_active;

    forever begin
      @(negedge vif.i_SPI_CS_n);
      pending_posedge_valid = 1'b0;
      burst_active           = 1'b1;

      while (burst_active) begin
        mosi_shreg = 8'h00;
        miso_shreg = 8'h00;

        for (int bit_idx = 0; bit_idx < 8 && burst_active; bit_idx++) begin
          // ---- Step 1: rising edge -> sample MOSI ----
          if (bit_idx == 0 && pending_posedge_valid) begin
            // Already consumed this rising edge during the previous
            // byte's burst-continuation lookahead - don't wait again.
            pending_posedge_valid = 1'b0;
          end
          else begin
            @(posedge vif.i_SPI_Clk or posedge vif.i_SPI_CS_n);
            if (vif.i_SPI_CS_n) begin
              // CS deasserted mid-byte - discard the partial byte and
              // stop this burst (guards against a hang, though normal
              // tests never do this).
              burst_active = 1'b0;
            end
          end

          if (burst_active) begin
            mosi_shreg = {mosi_shreg[6:0], vif.i_SPI_MOSI};

            // ---- Step 2: following falling edge -> sample MISO ----
            @(negedge vif.i_SPI_Clk or posedge vif.i_SPI_CS_n);
            if (vif.i_SPI_CS_n) begin
              burst_active = 1'b0;
            end
            else begin
              miso_shreg = {miso_shreg[6:0], vif.o_SPI_MISO};
            end
          end
        end

        if (burst_active) begin
          mon_txn           = new();
          mon_txn.mosi_data = mosi_shreg;
          mon_txn.miso_data = miso_shreg;

          // Determine whether another byte follows in this same burst:
          // race the next rising edge (next byte's bit 0) against CS_n
          // rising (end of burst).
          @(posedge vif.i_SPI_Clk or posedge vif.i_SPI_CS_n);
          if (vif.i_SPI_CS_n) begin
            mon_txn.cs_hold_after = 1'b0;
            burst_active          = 1'b0;   // burst has ended
          end
          else begin
            mon_txn.cs_hold_after = 1'b1;
            pending_posedge_valid = 1'b1;   // this edge = next byte's bit 0
          end

          mon_txn.print("MON");
          mon2scb_mbx.put(mon_txn.copy());
          mon2cov_mbx.put(mon_txn.copy());
        end
      end
    end
  endtask

endclass : monitor   

//====================================================
// Source: tb/coverage.sv
//====================================================
//=============================================================================
// File        : coverage.sv
// Description : Functional coverage for the SPI Slave verification
//               environment. Samples transactions coming from the
//               monitor, and also samples reset activity directly off
//               the interface.
//
//               Coverage goals (as per verification plan, docs/test_plan.md):
//                 - reset asserted/deasserted at least once
//                 - MOSI data values: include 0x00, 0xFF, alternating
//                   patterns, and general random spread (bins)
//                 - MISO data values: same bins as MOSI
//                 - back-to-back transfers (cs_hold_after = 1) exercised
//                 - single-byte transfers (cs_hold_after = 0) exercised
//                 - both clock edges of SCLK toggle during a transfer
//=============================================================================

class coverage;

  virtual spi_if.MONITOR vif;
  mailbox #(transaction) mon2cov_mbx;

  transaction cov_txn;   // sampled by covergroup below

  // ---------------------------------------------------------------
  // Covergroup: transaction-level coverage (data values, CS behavior)
  // ---------------------------------------------------------------
  covergroup cg_transaction;
    option.per_instance = 1;

    cp_mosi_data : coverpoint cov_txn.mosi_data {
      bins zero        = {8'h00};
      bins all_ones     = {8'hFF};
      bins alt_pattern  = {8'hAA, 8'h55};
      bins low_range    = {[8'h01 : 8'h3F]};
      bins mid_range    = {[8'h40 : 8'hBF]};
      bins high_range   = {[8'hC0 : 8'hFE]};
    }

    cp_miso_data : coverpoint cov_txn.miso_data {
      bins zero        = {8'h00};
      bins all_ones     = {8'hFF};
      bins alt_pattern  = {8'hAA, 8'h55};
      bins low_range    = {[8'h01 : 8'h3F]};
      bins mid_range    = {[8'h40 : 8'hBF]};
      bins high_range   = {[8'hC0 : 8'hFE]};
    }

    cp_cs_hold : coverpoint cov_txn.cs_hold_after {
      bins single_byte_txn = {0};  // CS deasserted right after this byte
      bins back_to_back    = {1};  // CS held low, another byte follows
    }

    // Cross MOSI data range with back-to-back behavior, to make sure
    // we see extreme data values both as standalone and burst transfers
    cx_data_burst : cross cp_mosi_data, cp_cs_hold;

  endgroup

  // ---------------------------------------------------------------
  // Covergroup: reset coverage, sampled directly on interface changes
  // ---------------------------------------------------------------
  covergroup cg_reset @(posedge vif.i_Clk);
    option.per_instance = 1;
    cp_reset_state : coverpoint vif.i_Rst_L {
      bins in_reset     = {0};
      bins out_of_reset = {1};
    }
  endgroup

  // ---------------------------------------------------------------
  // Covergroup: SPI clock edge activity while CS is asserted
  // ---------------------------------------------------------------
  covergroup cg_spi_clk @(posedge vif.i_SPI_Clk or negedge vif.i_SPI_Clk);
    option.per_instance = 1;
    cp_clk_edge : coverpoint vif.i_SPI_Clk iff (!vif.i_SPI_CS_n) {
      bins rising_seen  = {1};
      bins falling_seen = {0};
    }
  endgroup

  function new(virtual spi_if.MONITOR vif,
               mailbox #(transaction) mon2cov_mbx);
    this.vif         = vif;
    this.mon2cov_mbx = mon2cov_mbx;
    cg_transaction = new();
    cg_reset       = new();
    cg_spi_clk     = new();
  endfunction

  // -------------------------------------------------------------------
  // run: main coverage loop - waits for transactions from monitor and
  // samples the transaction covergroup. Reset/clk covergroups sample
  // themselves automatically since they are clocked covergroups.
  // -------------------------------------------------------------------
  task run();
    forever begin
      mon2cov_mbx.get(cov_txn);
      cg_transaction.sample();
    end
  endtask

  // -------------------------------------------------------------------
  // report: print final coverage summary
  // -------------------------------------------------------------------
  function void report();
    $display("=========================================================");
    $display("[COVERAGE] FINAL REPORT");
    $display("  Transaction coverage : %0.2f %%", cg_transaction.get_coverage());
    $display("  Reset coverage       : %0.2f %%", cg_reset.get_coverage());
    $display("  SPI clock coverage   : %0.2f %%", cg_spi_clk.get_coverage());
    $display("=========================================================");
  endfunction

endclass : coverage

//====================================================
// Source: tb/environment.sv
//====================================================
//=============================================================================
// File        : environment.sv
// Description : Top-level verification environment. Instantiates the
//               generator, driver, monitor, scoreboard, and coverage
//               components, connects them via mailboxes, and provides
//               simple run()/report() tasks for the test to call.
//
//               This is a plain SystemVerilog class (not uvm_env) -
//               construction and connection happen explicitly in the
//               constructor and build() method, which is easy to trace
//               for a fresher reading the code top-to-bottom.
//=============================================================================

class environment;

  // ---------------------------------------------------------------
  // Virtual interface handles (driver side, monitor side)
  // ---------------------------------------------------------------
  virtual spi_if.DRIVER  drv_vif;
  virtual spi_if.MONITOR mon_vif;

  // ---------------------------------------------------------------
  // Components
  // ---------------------------------------------------------------
  generator  gen;
  driver     drv;
  monitor    mon;
  scoreboard scb;
  coverage   cov;

  // ---------------------------------------------------------------
  // Mailboxes connecting the components
  // ---------------------------------------------------------------
  mailbox #(transaction) gen2drv_mbx;
  mailbox #(transaction) mon2scb_mbx;
  mailbox #(transaction) mon2cov_mbx;

  event drv_done;

  function new(virtual spi_if.DRIVER  drv_vif,
               virtual spi_if.MONITOR mon_vif);
    this.drv_vif = drv_vif;
    this.mon_vif = mon_vif;

    gen2drv_mbx = new();
    mon2scb_mbx = new();
    mon2cov_mbx = new();

    scb = new(mon_vif, mon2scb_mbx);
    gen = new(gen2drv_mbx, drv_done);
    drv = new(drv_vif, gen2drv_mbx, drv_done, scb);
    mon = new(mon_vif, mon2scb_mbx, mon2cov_mbx);
    cov = new(mon_vif, mon2cov_mbx);
  endfunction

  // -------------------------------------------------------------------
  // reset_env: applies reset through the driver before any test runs
  // -------------------------------------------------------------------
  task reset_env();
    drv.reset_dut();
  endtask

  // -------------------------------------------------------------------
  // run: starts all the always-running components (monitor, scoreboard,
  // coverage, driver) in parallel. Tests call gen.run_random() or
  // gen.run_directed() separately, then wait for the pipeline to drain.
  // -------------------------------------------------------------------
  task run();
    fork
      drv.run();
      mon.run();
      scb.run();
      cov.run();
    join_none
  endtask

  // -------------------------------------------------------------------
  // report: prints scoreboard + coverage summary at end of test
  // -------------------------------------------------------------------
  function void report();
    scb.report();
    cov.report();
  endfunction

endclass : environment

//====================================================
// Source: tb/test.sv
//====================================================
//=============================================================================
// File        : test.sv
// Description : Test class containing all test scenarios for the SPI
//               Slave verification environment. A single class holds
//               every test as a separate task; top_tb.sv selects which
//               one to run using a +TESTNAME plusarg (read via
//               $value$plusargs), so no elaborate factory/registration
//               mechanism is needed.
//
//               Available tests (see docs/test_plan.md for full details):
//                 smoke_test        - one simple byte transfer, sanity check
//                 random_test       - randomized bursts, the main regression
//                 reset_test        - reset asserted mid-transaction
//                 corner_test       - 0x00, 0xFF, alternating patterns
//                 back_to_back_test - long burst with CS held low throughout
//                 pattern_test      - walking-1/walking-0 data patterns
//=============================================================================

class test;

  environment env;

  virtual spi_if.DRIVER  drv_vif;
  virtual spi_if.MONITOR mon_vif;

  function new(virtual spi_if.DRIVER  drv_vif,
               virtual spi_if.MONITOR mon_vif);
    this.drv_vif = drv_vif;
    this.mon_vif = mon_vif;
    env = new(drv_vif, mon_vif);
  endfunction

  // -------------------------------------------------------------------
  // build_txn: small helper to build one transaction with given fields,
  // avoiding repetitive "new(); assign fields;" blocks in every test.
  // -------------------------------------------------------------------
  function transaction build_txn(bit [7:0] mosi_data,
                                  bit [7:0] miso_data,
                                  bit       cs_hold_after);
    transaction t = new();
    t.mosi_data     = mosi_data;
    t.miso_data     = miso_data;
    t.cs_hold_after = cs_hold_after;
    t.spi_mode      = 2'b00;
    return t;
  endfunction

  // =====================================================================
  // TEST 1: smoke_test
  // Simplest possible sanity test - one MOSI byte, one MISO byte,
  // single transfer, CS pulses low then high. If this fails, nothing
  // else in the DUT/TB integration is trustworthy.
  // =====================================================================
  task smoke_test();
    transaction q[$];
    $display("\n===================== SMOKE TEST =====================\n");
    env.reset_env();
    env.run();

    q.push_back(build_txn(8'hA5, 8'h3C, 1'b0));
    env.gen.run_directed(q);

    // Allow time for the single transfer + pipeline to complete
    repeat (120) @(posedge drv_vif.i_Clk);
    env.report();
  endtask

  // =====================================================================
  // TEST 2: random_test
  // Main regression workhorse - fully randomized transactions with a
  // healthy mix of single-byte and back-to-back bursts.
  // =====================================================================
  task random_test(int num_txns = 30);
    $display("\n===================== RANDOM TEST =====================\n");
    env.reset_env();
    env.run();

    env.gen.num_txns = num_txns;
    env.gen.run_random();

    // Wait long enough for all bursts to complete. Each byte takes
    // roughly 8 SPI clock periods; give generous margin.
    repeat (num_txns * 120) @(posedge drv_vif.i_Clk);
    env.report();
  endtask

  // =====================================================================
  // TEST 3: reset_test
  // Verifies the DUT recovers cleanly from a mid-transaction reset:
  // start a transfer, assert reset partway through, release reset,
  // then confirm a fresh transfer afterward works correctly.
  // =====================================================================
  task reset_test();
    transaction q[$];
    $display("\n===================== RESET TEST =====================\n");
    env.reset_env();
    env.run();

    // Kick off a transfer, then rip reset in the middle of it
    fork
      begin
        q.push_back(build_txn(8'h5A, 8'hC3, 1'b0));
        env.gen.run_directed(q);
      end
      begin
        // Wait partway into the byte, then assert reset asynchronously
        repeat (3) @(posedge drv_vif.i_SPI_Clk);
        $display("[TEST] Forcing i_Rst_L low mid-transaction at time %0t", $time);
        drv_vif.i_Rst_L <= 1'b0;
        repeat (5) @(posedge drv_vif.i_Clk);
        drv_vif.i_Rst_L <= 1'b1;
        $display("[TEST] Released i_Rst_L at time %0t", $time);
      end
    join

    // Bring CS back to idle and give the bus time to settle after the
    // forced reset before starting a clean transfer.
    drv_vif.i_SPI_CS_n <= 1'b1;
    repeat (10) @(posedge drv_vif.i_Clk);

    // Now confirm a completely normal transfer works after reset
    q.delete();
    q.push_back(build_txn(8'h11, 8'h22, 1'b0));
    env.gen.run_directed(q);
    repeat (120) @(posedge drv_vif.i_Clk);

    env.report();
  endtask

  // =====================================================================
  // TEST 4: corner_test
  // Directed test focused on edge-value data: all-zeros, all-ones, and
  // alternating bit patterns, both as MOSI and MISO data.
  // =====================================================================
  task corner_test();
    transaction q[$];
    $display("\n===================== CORNER CASE TEST =====================\n");
    env.reset_env();
    env.run();

    q.push_back(build_txn(8'h00, 8'h00, 1'b1)); // all zeros, hold CS
    q.push_back(build_txn(8'hFF, 8'hFF, 1'b1)); // all ones, hold CS
    q.push_back(build_txn(8'hAA, 8'h55, 1'b1)); // alternating pattern
    q.push_back(build_txn(8'h55, 8'hAA, 1'b0)); // inverse pattern, end burst

    env.gen.run_directed(q);
    repeat (q.size() * 120) @(posedge drv_vif.i_Clk);
    env.report();
  endtask

  // =====================================================================
  // TEST 5: back_to_back_test
  // Verifies multiple bytes transferred in one continuous CS_n-low
  // burst (this exercises the DUT's ability to keep shifting bytes
  // without CS toggling between every byte).
  // =====================================================================
  task back_to_back_test(int burst_len = 8);
    transaction q[$];
    $display("\n===================== BACK-TO-BACK TEST =====================\n");
    env.reset_env();
    env.run();

    for (int i = 0; i < burst_len; i++) begin
      bit last = (i == burst_len - 1);
      q.push_back(build_txn(8'(i), 8'(burst_len - i), !last));
    end

    env.gen.run_directed(q);
    repeat (burst_len * 120) @(posedge drv_vif.i_Clk);
    env.report();
  endtask

  // =====================================================================
  // TEST 6: pattern_test
  // Walking-1 and walking-0 data patterns on MOSI, useful for catching
  // any bit-ordering mistakes in either the DUT or the testbench itself.
  // =====================================================================
  task pattern_test();
    transaction q[$];
    $display("\n===================== DATA PATTERN TEST =====================\n");
    env.reset_env();
    env.run();

    // Walking 1s
    for (int i = 0; i < 8; i++) begin
      q.push_back(build_txn(8'h01 << i, 8'h80 >> i, 1'b1));
    end
    // Walking 0s (inverse), last one ends the burst
    for (int i = 0; i < 8; i++) begin
      bit last = (i == 7);
      q.push_back(build_txn(~(8'h01 << i), ~(8'h80 >> i), !last));
    end

    env.gen.run_directed(q);
    repeat (q.size() * 120) @(posedge drv_vif.i_Clk);
    env.report();
  endtask

endclass : test 

//====================================================
// Source: tb/top_tb.sv
//====================================================
//=============================================================================
// File        : top_tb.sv
// Description : Top-level testbench module. Responsibilities:
//                 - generate the system clock (i_Clk)
//                 - instantiate the spi_if interface
//                 - instantiate the SPI_Slave DUT and connect it to the
//                   interface
//                 - bind in the protocol assertions module
//                 - select and run one test based on +TESTNAME plusarg
//                 - dump waveforms (VCD) for debug
//
//               Run with, e.g.:
//                 make run TEST=smoke_test
//               which passes +TESTNAME=smoke_test to the simulator.
//=============================================================================

`timescale 1ns / 1ps

module top_tb;

  // ---------------------------------------------------------------
  // System clock generation: 100 MHz (10ns period)
  // Must be at least 4x faster than the SPI clock the driver
  // generates (10 MHz / 100ns period), per DUT requirements.
  // ---------------------------------------------------------------
  logic i_Clk;
  initial i_Clk = 1'b0;
  always #5 i_Clk = ~i_Clk;   // 10ns period -> 100MHz

  // ---------------------------------------------------------------
  // Interface instantiation
  // ---------------------------------------------------------------
  spi_if u_spi_if (.i_Clk(i_Clk));

  // ---------------------------------------------------------------
  // DUT instantiation - SPI_MODE=0 (CPOL=0, CPHA=0), matching the
  // driver's bit-banging timing in driver.sv
  // ---------------------------------------------------------------
  SPI_Slave #(
    .SPI_MODE (0)
  ) u_dut (
    .i_Rst_L     (u_spi_if.i_Rst_L),
    .i_Clk       (u_spi_if.i_Clk),

    .o_RX_DV     (u_spi_if.o_RX_DV),
    .o_RX_Byte   (u_spi_if.o_RX_Byte),

    .i_TX_DV     (u_spi_if.i_TX_DV),
    .i_TX_Byte   (u_spi_if.i_TX_Byte),

    .i_SPI_Clk   (u_spi_if.i_SPI_Clk),
    .o_SPI_MISO  (u_spi_if.o_SPI_MISO),
    .i_SPI_MOSI  (u_spi_if.i_SPI_MOSI),
    .i_SPI_CS_n  (u_spi_if.i_SPI_CS_n)
  );

  // ---------------------------------------------------------------
  // Protocol assertions - bound to the interface, see
  // assertions/spi_assertions.sv for details
  // ---------------------------------------------------------------
  spi_assertions u_spi_assertions (
    .i_Clk       (u_spi_if.i_Clk),
    .i_Rst_L     (u_spi_if.i_Rst_L),
    .i_SPI_Clk   (u_spi_if.i_SPI_Clk),
    .i_SPI_MOSI  (u_spi_if.i_SPI_MOSI),
    .i_SPI_CS_n  (u_spi_if.i_SPI_CS_n),
    .o_SPI_MISO  (u_spi_if.o_SPI_MISO),
    .o_RX_DV     (u_spi_if.o_RX_DV),
    .o_RX_Byte   (u_spi_if.o_RX_Byte)
  );

  // ---------------------------------------------------------------
  // Waveform dumping (VCD, viewable with GTKWave or Verdi)
  // ---------------------------------------------------------------
  initial begin
    $dumpfile("spi_slave_tb.vcd"); 
    $dumpvars(0, top_tb);
  end

  // ---------------------------------------------------------------
  // Test selection and execution
  // ---------------------------------------------------------------
  test t;
  string test_name;

  initial begin
    t = new(u_spi_if.DRIVER, u_spi_if.MONITOR);

    if (!$value$plusargs("TESTNAME=%s", test_name)) begin
      test_name = "smoke_test";   // default test if none specified
    end

    $display("=========================================================");
    $display(" SPI SLAVE VERIFICATION - Starting test: %0s", test_name);
    $display("=========================================================");

    case (test_name)
      "smoke_test"        : t.smoke_test();
      "random_test"        : t.random_test();
      "reset_test"          : t.reset_test();
      "corner_test"         : t.corner_test();
      "back_to_back_test"   : t.back_to_back_test();
      "pattern_test"        : t.pattern_test();
      default : begin
        $error("[TOP_TB] Unknown TESTNAME '%0s'. Valid options: smoke_test, random_test, reset_test, corner_test, back_to_back_test, pattern_test",
                test_name);
      end
    endcase

    $display("=========================================================");
    $display(" SPI SLAVE VERIFICATION - Test '%0s' complete", test_name);
    $display("=========================================================");

    #100;
    $finish;
  end

  // ---------------------------------------------------------------
  // Simulation timeout watchdog - prevents a hung testbench from
  // running forever (e.g. if a mailbox blocks unexpectedly)
  // ---------------------------------------------------------------
  initial begin
    #1_000_000; // 1ms of simulated time, generous for these tests
    $error("[TOP_TB] TIMEOUT - simulation did not finish in time. Possible hang.");
    $finish;
  end

endmodule : top_tb
