# concat_tb_for_eda_playground.ps1
# Windows version of the Bash concatenation script

$Root = Split-Path $PSScriptRoot -Parent
$OutFile = Join-Path $PSScriptRoot "combined_tb.sv"

$Files = @(
"tb/spi_if.sv",
"assertions/spi_assertions.sv",
"tb/transaction.sv",
"tb/generator.sv",
"tb/scoreboard.sv",
"tb/driver.sv",
"tb/monitor.sv",
"tb/coverage.sv",
"tb/environment.sv",
"tb/test.sv",
"tb/top_tb.sv"
)

Set-Content $OutFile "// Auto-generated by concat_tb_for_eda_playground.ps1"
Add-Content $OutFile "// Paste this into the EDA Playground Testbench pane."
Add-Content $OutFile ""

foreach($file in $Files)
{
    Add-Content $OutFile ""
    Add-Content $OutFile "//===================================================="
    Add-Content $OutFile "// Source: $file"
    Add-Content $OutFile "//===================================================="

    Get-Content (Join-Path $Root $file) | Add-Content $OutFile
}

Write-Host ""
Write-Host "Combined testbench created:"
Write-Host $OutFile 