#!/usr/bin/env bash
#==============================================================================
# concat_tb_for_eda_playground.sh
#
# Concatenates all testbench files in the correct class-dependency order
# into a single file, ready to paste into EDA Playground's "Testbench"
# pane (see docs/how_to_run.md, Step 4). Saves you from manually copying
# 11 files one at a time.
#
# Usage:
#   bash scripts/concat_tb_for_eda_playground.sh
#
# Output:
#   scripts/combined_tb.sv
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUT_FILE="$SCRIPT_DIR/combined_tb.sv"

FILES=(
  "tb/spi_if.sv"
  "assertions/spi_assertions.sv"
  "tb/transaction.sv"
  "tb/generator.sv"
  "tb/scoreboard.sv"
  "tb/driver.sv"
  "tb/monitor.sv"
  "tb/coverage.sv"
  "tb/environment.sv"
  "tb/test.sv"
  "tb/top_tb.sv"
)

echo "// Auto-generated by concat_tb_for_eda_playground.sh" > "$OUT_FILE"
echo "// Paste this whole file into EDA Playground's Testbench pane." >> "$OUT_FILE"
echo "// Paste rtl/SPI_Slave.v into the Design pane separately." >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

for f in "${FILES[@]}"; do
  echo "" >> "$OUT_FILE"
  echo "//=====================================================================" >> "$OUT_FILE"
  echo "// Source: $f" >> "$OUT_FILE"
  echo "//=====================================================================" >> "$OUT_FILE"
  cat "$ROOT_DIR/$f" >> "$OUT_FILE"
done

echo "Combined testbench written to: $OUT_FILE"
echo "Paste its contents into the EDA Playground Testbench pane."
